POST http://localhost:3000/api/sendEmail-otp
content-type: application/json

{
    "email":"potduksheamite@gsmail.com"
}

###
POST http://localhost:3000/api/signup
content-type: application/json

{
    "name":"amit",
    "email":"potduksheamite@gsmail.com",
    "mobile":"9359814269777",
    "password":"123",
    "otp":"1464"
}

###
POST http://localhost:3000/api/forgotpassword
content-type: application/json

{
    "email":"potdukheamit@gmail.com",
    "newPassword":"12345",
    "otp":"2153"
}

###
POST http://localhost:3000/api/verify-otp
content-type: application/json

{
    "email":"potdukheamit@gmail.com",
    "otp":"2153"
}

###
POST http://localhost:3000/api/signin
content-type: application/json

{
    "email":"potduksheamite@gsmail.com",
    "password":"123"
}

